const EAST_COAST_RUNTIME_MATERIAL_DEFS = {
  Birch_Bark_01: {
    name: 'Birch_Bark_01',
    mapTo: 'Birch_Bark_01',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/birch/t_birch_bark/t_birch_bark_ao.data.png',
      baseColorMap: '/assets/materials/tree/birch/t_birch_bark/t_birch_bark_b.color.png',
      normalMap: '/assets/materials/tree/birch/t_birch_bark/t_birch_bark_nm.normal.png',
      roughnessMap: '/assets/materials/tree/birch/t_birch_bark/t_birch_bark_r.data.png',
    }],
    annotation: 'NATURE',
    groundType: 'WOOD',
  },
  Birch_Branch_01: {
    name: 'Birch_Branch_01',
    mapTo: 'Birch_Branch_01',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/birch/t_birch_branch/t_birch_branch_ao.data.png',
      baseColorMap: '/assets/materials/tree/birch/t_birch_branch/t_birch_branch_b.color.png',
      normalMap: '/assets/materials/tree/birch/t_birch_branch/t_birch_branch_nm.normal.png',
      opacityMap: '/assets/materials/tree/birch/t_birch_branch/t_birch_branch_o.data.png',
      roughnessMap: '/assets/materials/tree/birch/t_birch_branch/t_birch_branch_r.data.png',
    }],
    alphaRef: 60,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    groundType: 'WOOD',
  },
  Birch_Leaves_01: {
    name: 'Birch_Leaves_01',
    mapTo: 'Birch_Leaves_01',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/birch/t_birch_leaves/t_birch_leaves_ao.data.png',
      baseColorMap: '/assets/materials/tree/birch/t_birch_leaves/t_birch_leaves_b.color.png',
      normalMap: '/assets/materials/tree/birch/t_birch_leaves/t_birch_leaves_nm.normal.png',
      opacityMap: '/assets/materials/tree/birch/t_birch_leaves/t_birch_leaves_o.data.png',
      roughnessMap: '/assets/materials/tree/birch/t_birch_leaves/t_birch_leaves_r.data.png',
    }],
    alphaRef: 100,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    groundType: 'LEAVES_THIN',
    translucentBlendOp: 'None',
  },
  m_birch_leaves_distant: {
    name: 'm_birch_leaves_distant',
    mapTo: 'm_birch_leaves_distant',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/birch/t_birch_leaves_distant/t_birch_leaves_distant_ao.data.png',
      baseColorMap: '/assets/materials/tree/birch/t_birch_leaves_distant/t_birch_leaves_distant_b.color.png',
      normalMap: '/assets/materials/tree/birch/t_birch_leaves_distant/t_birch_leaves_distant_nm.normal.png',
      opacityMap: '/assets/materials/tree/birch/t_birch_leaves_distant/t_birch_leaves_distant_o.data.png',
      roughnessMap: '/assets/materials/tree/birch/t_birch_leaves_distant/t_birch_leaves_distant_r.data.png',
    }],
    alphaRef: 80,
    alphaTest: true,
    doubleSided: true,
  },
  beech_blocker: {
    name: 'beech_blocker',
    mapTo: 'beech_blocker',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/beech/t_beech_blocker/t_beech_blocker_ao.data.png',
      baseColorMap: '/assets/materials/tree/beech/t_beech_blocker/t_beech_blocker_b.color.png',
      normalMap: '/assets/materials/tree/beech/t_beech_blocker/t_beech_blocker_nm.normal.png',
      opacityMap: '/assets/materials/tree/beech/t_beech_blocker/t_beech_blocker_o.data.png',
      roughnessMap: '/assets/materials/tree/beech/t_beech_blocker/t_beech_blocker_r.data.png',
    }],
    alphaRef: 90,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    groundType: 'WOOD',
  },
  beech_branch_01: {
    name: 'beech_branch_01',
    mapTo: 'beech_branch_01',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/beech/t_beech_branch_01/t_beech_branch_ao.data.png',
      baseColorMap: '/assets/materials/tree/beech/t_beech_branch_01/t_beech_branch_b.color.png',
      normalMap: '/assets/materials/tree/beech/t_beech_branch_01/t_beech_branch_nm.normal.png',
      opacityMap: '/assets/materials/tree/beech/t_beech_branch_01/t_beech_branch_o.data.png',
      roughnessMap: '/assets/materials/tree/beech/t_beech_branch_01/t_beech_branch_r.data.png',
    }],
    alphaRef: 75,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    groundType: 'WOOD',
  },
  beech_leaves: {
    name: 'beech_leaves',
    mapTo: 'beech_leaves',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/beech/t_beech_leaves/t_beech_leaves_ao.data.png',
      baseColorMap: '/assets/materials/tree/beech/t_beech_leaves/t_beech_leaves_b.color.png',
      normalMap: '/assets/materials/tree/beech/t_beech_leaves/t_beech_leaves_nm.normal.png',
      opacityMap: '/assets/materials/tree/beech/t_beech_leaves/t_beech_leaves_o.data.png',
      roughnessMap: '/assets/materials/tree/beech/t_beech_leaves/t_beech_leaves_r.data.png',
    }],
    alphaRef: 105,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    groundType: 'LEAVES_THIN',
  },
  beech_trunk: {
    name: 'beech_trunk',
    mapTo: 'beech_trunk',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/beech/t_beech_trunk/t_beech_bark_ao.data.png',
      baseColorMap: '/assets/materials/tree/beech/t_beech_trunk/t_beech_bark_b.color.png',
      normalMap: '/assets/materials/tree/beech/t_beech_trunk/t_beech_bark_nm.normal.png',
      roughnessMap: '/assets/materials/tree/beech/t_beech_trunk/t_beech_bark_r.data.png',
    }],
    alphaRef: 10,
    alphaTest: true,
    annotation: 'NATURE',
    groundType: 'WOOD',
  },
  m_beech_leaves_distant: {
    name: 'm_beech_leaves_distant',
    mapTo: 'm_beech_leaves_distant',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/beech/t_beech_leaves_distant/t_beech_leaves_distant_ao.data.png',
      baseColorMap: '/assets/materials/tree/beech/t_beech_leaves_distant/t_beech_leaves_distant_b.color.png',
      normalMap: '/assets/materials/tree/beech/t_beech_leaves_distant/t_beech_leaves_distant_nm.normal.png',
      opacityMap: '/assets/materials/tree/beech/t_beech_leaves_distant/t_beech_leaves_distant_o.data.png',
      roughnessMap: '/assets/materials/tree/beech/t_beech_leaves_distant/t_beech_leaves_distant_r.data.png',
    }],
    alphaRef: 80,
    alphaTest: true,
    doubleSided: true,
  },
  m_beech_merged_foliage: {
    name: 'm_beech_merged_foliage',
    mapTo: 'm_beech_merged_foliage',
    class: 'Material',
    Stages: [{
      colorMap: '/assets/materials/tree/beech/m_beech_merged_foliage/t_beech_merged_foliage_d.color.png',
      normalMap: '/assets/materials/tree/beech/m_beech_merged_foliage/t_beech_merged_foliage_nm.normal.png',
      useAnisotropic: true,
    }],
    alphaRef: 100,
    alphaTest: true,
    doubleSided: true,
  },
  leaves_strong: {
    name: 'leaves_strong',
    mapTo: 'leaves_strong',
    class: 'Material',
    Stages: [{}, {}, {}, {}],
    groundType: 'leaves_strong',
    groundDepth: 0.3000000119,
  },
  BNGGrass: {
    name: 'BNGGrass',
    mapTo: 'unmapped_mat',
    class: 'Material',
    Stages: [{
      colorMap: '/assets/materials/foliage/grass/BNGGrass/t_grass_01_d.color.png',
      normalMap: '/assets/materials/foliage/grass/BNGGrass/t_grass_01_nm.normal.png',
      specularMap: '/assets/materials/foliage/grass/BNGGrass/t_grass_01_s.color.png',
      useAnisotropic: true,
    }],
    alphaRef: 60,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    translucentBlendOp: 'None',
  },
  eca_bld_trim_wood: {
    class: 'Material',
    name: 'eca_bld_trim_wood',
    mapTo: 'eca_bld_trim_wood',
    annotation: 'BUILDINGS',
    Stages: [{
      colorMap: '/levels/east_coast_usa/art/shapes/buildings/eca_bld_trim_wood_d.dds',
      normalMap: '/levels/east_coast_usa/art/shapes/buildings/eca_bld_trim_wood_n.dds',
      specularMap: '/levels/east_coast_usa/art/shapes/buildings/eca_bld_trim_wood_s.dds',
      diffuseColor: [1, 1, 1, 1],
    }],
    translucentBlendOp: 'None',
  },
  eca_bld_wood: {
    class: 'Material',
    name: 'eca_bld_wood',
    mapTo: 'eca_bld_wood',
    annotation: 'BUILDINGS',
    Stages: [{
      colorMap: '/levels/east_coast_usa/art/shapes/buildings/eca_bld_wood_d.dds',
      normalMap: '/levels/east_coast_usa/art/shapes/buildings/eca_bld_wood_n.dds',
      specularMap: '/levels/east_coast_usa/art/shapes/buildings/eca_bld_wood_s.dds',
      diffuseColor: [1, 1, 1, 1],
    }],
    translucentBlendOp: 'None',
  },
  lumber_raw: {
    class: 'Material',
    name: 'lumber_raw',
    mapTo: 'lumber_raw',
    annotation: 'BUILDINGS',
    Stages: [{
      colorMap: '/levels/east_coast_usa/art/shapes/misc/lumber_raw_d.dds',
      normalMap: '/levels/east_coast_usa/art/shapes/misc/lumber_raw_n.dds',
      specularMap: '/levels/east_coast_usa/art/shapes/misc/lumber_raw_s.dds',
      diffuseColor: [1, 1, 1, 1],
    }],
    translucentBlendOp: 'None',
  },
};

const ITALY_RUNTIME_MATERIAL_DEFS = {
  Oak_bark_01: {
    name: 'Oak_bark_01',
    mapTo: 'Oak_bark_01',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/oak/t_oak_bark/t_oak_bark_ao.data.png',
      baseColorMap: '/assets/materials/tree/oak/t_oak_bark/t_oak_bark_b.color.png',
      normalMap: '/assets/materials/tree/oak/t_oak_bark/t_oak_bark_nm.normal.png',
      roughnessMap: '/assets/materials/tree/oak/t_oak_bark/t_oak_bark_r.data.png',
    }],
    annotation: 'NATURE',
    groundType: 'WOOD',
  },
  holm_oak_branches: {
    name: 'holm_oak_branches',
    mapTo: 'holm_oak_branches',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/holm_oak/t_holm_oak_branches/t_holm_oak_branches_ao.data.png',
      baseColorMap: '/assets/materials/tree/holm_oak/t_holm_oak_branches/t_holm_oak_branches_b.color.png',
      normalMap: '/assets/materials/tree/holm_oak/t_holm_oak_branches/t_holm_oak_branches_nm.normal.png',
      opacityMap: '/assets/materials/tree/holm_oak/t_holm_oak_branches/t_holm_oak_branches_o.data.png',
      roughnessMap: '/assets/materials/tree/holm_oak/t_holm_oak_branches/t_holm_oak_branches_r.data.png',
    }],
    alphaRef: 70,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    translucentBlendOp: 'None',
  },
  oak_leaves_02: {
    name: 'oak_leaves_02',
    mapTo: 'oak_leaves_02',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/oak/t_oak_leaves_01/t_oak_leaves_ao.data.png',
      baseColorMap: '/assets/materials/tree/oak/t_italy_oak_leaves_02/t_italy_oak_leaves_02_b.color.png',
      normalMap: '/assets/materials/tree/oak/t_oak_leaves_01/t_oak_leaves_nm.normal.png',
      opacityMap: '/assets/materials/tree/oak/t_oak_leaves_01/t_oak_leaves_o.data.png',
      roughnessMap: '/assets/materials/tree/oak/t_oak_leaves_01/t_oak_leaves_r.data.png',
    }],
    alphaRef: 110,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    groundType: 'LEAVES_THIN',
    translucentZWrite: true,
  },
  m_oak_leaves_02_distant: {
    name: 'm_oak_leaves_02_distant',
    mapTo: 'm_oak_leaves_02_distant',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/oak/t_oak_leaves_distant/t_oak_leaves_distant_ao.data.png',
      baseColorMap: '/assets/materials/tree/oak/t_italy_oak_leaves_02_distant/t_italy_oak_leaves_02_distant_b.color.png',
      normalMap: '/assets/materials/tree/oak/t_oak_leaves_distant/t_oak_leaves_distant_nm.normal.png',
      opacityMap: '/assets/materials/tree/oak/t_oak_leaves_distant/t_oak_leaves_distant_o.data.png',
      roughnessMap: '/assets/materials/tree/oak/t_oak_leaves_distant/t_oak_leaves_distant_r.data.png',
    }],
    alphaRef: 80,
    alphaTest: true,
    doubleSided: true,
  },
  leaves_strong: {
    name: 'leaves_strong',
    mapTo: 'leaves_strong',
    class: 'Material',
    Stages: [{}, {}, {}, {}],
    groundType: 'leaves_strong',
    groundDepth: 0.3000000119,
  },
  leaves_thin: {
    name: 'leaves_thin',
    mapTo: 'leaves_thin',
    class: 'Material',
    Stages: [{}, {}, {}, {}],
    annotation: 'NATURE',
    groundType: 'leaves_thin',
    groundDepth: 1,
  },
  generibush_leaves: {
    name: 'generibush_leaves',
    mapTo: 'generibush_leaves',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/foliage/bush/t_generibush_leaves/t_generic_bush_ao.data.png',
      baseColorMap: '/assets/materials/foliage/bush/t_generibush_leaves/t_generic_bush_b.color.png',
      normalMap: '/assets/materials/foliage/bush/t_generibush_leaves/t_generic_bush_nm.normal.png',
      opacityMap: '/assets/materials/foliage/bush/t_generibush_leaves/t_generic_bush_o.data.png',
      roughnessMap: '/assets/materials/foliage/bush/t_generibush_leaves/t_generic_bush_r.data.png',
    }],
    alphaRef: 90,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 1,
  },
  scots_pine: {
    name: 'scots_pine',
    mapTo: 'scots_pine',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/scots_pine/t_scots_pine/t_scots_pine_ao.data.png',
      baseColorMap: '/assets/materials/tree/scots_pine/t_scots_pine/t_scots_pine_b.color.png',
      normalMap: '/assets/materials/tree/scots_pine/t_scots_pine/t_scots_pine_nm.normal.png',
      opacityMap: '/assets/materials/tree/scots_pine/t_scots_pine/t_scots_pine_o.data.png',
      roughnessMap: '/assets/materials/tree/scots_pine/t_scots_pine/t_scots_pine_r.data.png',
    }],
    alphaRef: 80,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    groundType: 'FOLIAGE_THIN',
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 1,
  },
  scots_pine_branches: {
    name: 'scots_pine_branches',
    mapTo: 'scots_pine_branches',
    class: 'Material',
    Stages: [{
      baseColorMap: '/assets/materials/tree/scots_pine/t_scots_pine_branches/t_scots_pine_branches_b.color.png',
      detailMap: '/assets/materials/tree/tropical/tro_tree_1_trunk/t_tropical_bark_variation_1_detail.data.png',
      detailNormalMap: '/assets/materials/tree/cork_oak/t_cork_oak_trunk/t_cork_oak_trunk_nm.normal.png',
      detailNormalMapStrength: 3,
      normalMap: '/assets/materials/tree/scots_pine/t_scots_pine_branches/t_scots_pine_branches_nm.normal.png',
      opacityMap: '/assets/materials/tree/scots_pine/t_scots_pine_branches/t_scots_pine_branches_o.data.png',
      roughnessMap: '/assets/materials/tree/scots_pine/t_scots_pine_branches/t_scots_pine_branches_r.data.png',
    }],
    alphaRef: 80,
    alphaTest: true,
    annotation: 'NATURE',
    groundType: 'FOLIAGE_THIN',
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 0.00999999978,
  },
  scots_pine_trunk: {
    name: 'scots_pine_trunk',
    mapTo: 'scots_pine_trunk',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/scots_pine/t_scots_pine_trunk/t_scots_pine_bark_ao.data.png',
      baseColorMap: '/assets/materials/tree/scots_pine/t_scots_pine_trunk/t_scots_pine_bark_b.color.png',
      detailMap: '/assets/materials/tree/tropical/tro_tree_1_trunk/t_tropical_bark_variation_1_detail.data.png',
      detailNormalMap: '/assets/materials/tree/t_pine/t_pine_bark/t_pine_bark_nm.normal.png',
      detailNormalMapStrength: 3,
      detailScale: [5, 0.75],
      normalMap: '/assets/materials/tree/scots_pine/t_scots_pine_trunk/t_scots_pine_bark_nm.normal.png',
      roughnessMap: '/assets/materials/tree/scots_pine/t_scots_pine_trunk/t_scots_pine_bark_r.data.png',
    }],
    alphaRef: 85,
    annotation: 'NATURE',
    groundType: 'WOOD',
  },
  GrassMiddle: {
    name: 'GrassMiddle',
    mapTo: 'GrassMiddle',
    class: 'Material',
    Stages: [{
      colorMap: '/assets/materials/foliage/grass/GrassMiddle/Grass_Middle_d.dds',
      normalMap: '/assets/materials/foliage/grass/GrassDry/Grass_green_n.normal.png',
      specularMap: '/assets/materials/foliage/grass/GrassDry/Grass_green_s.color.png',
      useAnisotropic: true,
    }],
    alphaRef: 95,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    groundType: 'GRASS',
    translucentBlendOp: 'None',
  },
};

const UTAH_RUNTIME_MATERIAL_DEFS = {
  juniper_bark: {
    name: 'juniper_bark',
    mapTo: 'juniper_bark',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/juniper/t_juniper_bark/t_juniper_bark_ao.data.png',
      baseColorMap: '/assets/materials/tree/juniper/t_juniper_bark/t_juniper_bark_b.color.png',
      detailMap: '/assets/materials/tree/tropical/tro_tree_1_trunk/t_tropical_bark_variation_1_detail.data.png',
      detailNormalMap: '/assets/materials/tree/tropical/tro_tree_1_trunk/t_tro_bark_01_detail_nm.normal.png',
      detailNormalMapStrength: 2,
      detailScale: [2, 0.5],
      normalMap: '/assets/materials/tree/juniper/t_juniper_bark/t_juniper_bark_nm.normal.png',
      normalMapStrength: 1.5,
      roughnessMap: '/assets/materials/tree/juniper/t_juniper_bark/t_juniper_bark_r.data.png',
      specular: [0.203921586, 0.203921586, 0.203921586, 1],
    }],
    alphaRef: 70,
    alphaTest: true,
    groundType: 'WOOD',
  },
  Juniper_bark: {
    name: 'Juniper_bark',
    mapTo: 'Juniper_bark',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/juniper/t_juniper_bark/t_juniper_bark_ao.data.png',
      baseColorMap: '/assets/materials/tree/juniper/t_juniper_bark/t_juniper_bark_b.color.png',
      detailMap: '/assets/materials/tree/tropical/tro_tree_1_trunk/t_tropical_bark_variation_1_detail.data.png',
      detailNormalMap: '/assets/materials/tree/tropical/tro_tree_1_trunk/t_tro_bark_01_detail_nm.normal.png',
      detailNormalMapStrength: 2,
      detailScale: [2, 0.5],
      normalMap: '/assets/materials/tree/juniper/t_juniper_bark/t_juniper_bark_nm.normal.png',
      normalMapStrength: 1.5,
      roughnessMap: '/assets/materials/tree/juniper/t_juniper_bark/t_juniper_bark_r.data.png',
      specular: [0.203921586, 0.203921586, 0.203921586, 1],
    }],
    alphaRef: 70,
    alphaTest: true,
    groundType: 'WOOD',
  },
  juniper_dry: {
    name: 'juniper_dry',
    mapTo: 'juniper_dry',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/juniper/t_juniper_dry/t_juniper_dry_ao.data.png',
      baseColorMap: '/assets/materials/tree/juniper/t_juniper_dry/t_juniper_dry_b.color.png',
      normalMap: '/assets/materials/tree/juniper/t_juniper_dry/t_juniper_dry_nm.normal.png',
      opacityMap: '/assets/materials/tree/juniper/t_juniper_dry/t_juniper_dry_o.data.png',
      roughnessMap: '/assets/materials/tree/juniper/t_juniper_dry/t_juniper_dry_r.data.png',
      specular: [0.145098045, 0.145098045, 0.145098045, 1],
    }],
    alphaRef: 80,
    alphaTest: true,
    doubleSided: true,
    groundType: 'WOOD',
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 0.699999988,
  },
  juniper_leave_01: {
    name: 'juniper_leave_01',
    mapTo: 'juniper_leave_01',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/juniper/t_juniper_leave_01/t_juniper_leaves_ao.data.png',
      baseColorMap: '/assets/materials/tree/juniper/t_juniper_leave_01/t_juniper_leaves_b.color.png',
      normalMap: '/assets/materials/tree/juniper/t_juniper_leave_01/t_juniper_leaves_nm.normal.png',
      normalMapStrength: 0.5,
      opacityMap: '/assets/materials/tree/juniper/t_juniper_leave_01/t_juniper_leaves_o.data.png',
      roughnessMap: '/assets/materials/tree/juniper/t_juniper_leave_01/t_juniper_leaves_r.data.png',
      specular: [0.156862751, 0.156862751, 0.156862751, 1],
    }],
    alphaRef: 140,
    alphaTest: true,
    doubleSided: true,
    groundType: 'LEAVES_THIN',
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 1,
    translucentBlendOp: 'None',
  },
  m_juniper_leaves_01_distant: {
    name: 'm_juniper_leaves_01_distant',
    mapTo: 'm_juniper_leaves_01_distant',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/juniper/t_juniper_leave_01_distant/t_juniper_leaves_distant_ao.data.png',
      baseColorMap: '/assets/materials/tree/juniper/t_juniper_leave_01_distant/t_juniper_leaves_distant_b.color.png',
      normalMap: '/assets/materials/tree/juniper/t_juniper_leave_01_distant/t_juniper_leaves_distant_nm.normal.png',
      opacityMap: '/assets/materials/tree/juniper/t_juniper_leave_01_distant/t_juniper_leaves_distant_o.data.png',
      roughnessMap: '/assets/materials/tree/juniper/t_juniper_leave_01_distant/t_juniper_leaves_distant_r.data.png',
    }],
    alphaRef: 80,
    alphaTest: true,
    doubleSided: true,
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 1,
  },
  leaves_strong: {
    name: 'leaves_strong',
    mapTo: 'leaves_strong',
    class: 'Material',
    Stages: [{}, {}, {}, {}],
    groundType: 'leaves_strong',
    groundDepth: 0.6000000238418579,
  },
  dry_grass: {
    name: 'dry_grass',
    mapTo: 'dry_grass',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/foliage/grass/t_utah_dry_grass/t_utah_dry_grass_ao.data.png',
      baseColorFactor: [0.905882418, 0.905882418, 0.905882418, 1],
      baseColorMap: '/assets/materials/foliage/grass/t_utah_dry_grass/t_utah_dry_grass_b.color.png',
      normalMap: '/assets/materials/foliage/grass/t_utah_dry_grass/t_utah_dry_grass_nm.normal.png',
      opacityMap: '/assets/materials/foliage/grass/t_utah_dry_grass/t_utah_dry_grass_o.data.png',
      roughnessMap: '/assets/materials/foliage/grass/t_utah_dry_grass/t_utah_dry_grass_r.data.png',
      specular: [0.988235354, 0.988235354, 0.988235354, 1],
    }],
    alphaRef: 60,
    alphaTest: true,
    annotation: 'GRASS',
    doubleSided: true,
    groundType: 'GRASS',
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 1,
    translucentBlendOp: 'None',
  },
  catchfence: {
    name: 'catchfence',
    mapTo: 'catchfence',
    class: 'Material',
    Stages: [{
      diffuseColor: [0.72, 0.72, 0.72, 1],
    }],
    translucentBlendOp: 'None',
  },
};

const AUTOMATION_TEST_TRACK_RUNTIME_MATERIAL_DEFS = {
  cork_oak: {
    name: 'cork_oak',
    mapTo: 'cork_oak',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/cork_oak/t_cork_oak/t_cork_oak_ao.data.png',
      baseColorMap: '/assets/materials/tree/cork_oak/t_cork_oak_autumn/t_cork_oak_autumn_b.color.png',
      normalMap: '/assets/materials/tree/cork_oak/t_cork_oak/t_cork_oak_nm.normal.png',
      normalMapStrength: 2,
      opacityMap: '/assets/materials/tree/cork_oak/t_cork_oak/t_cork_oak_o.data.png',
      roughnessMap: '/assets/materials/tree/cork_oak/t_cork_oak/t_cork_oak_r.data.png',
    }],
    alphaRef: 100,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    groundType: 'WOOD',
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 1,
  },
  cork_oak_trunk: {
    name: 'cork_oak_trunk',
    mapTo: 'cork_oak_trunk',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/cork_oak/t_cork_oak_trunk/t_cork_oak_trunk_ao.data.png',
      baseColorMap: '/assets/materials/tree/cork_oak/t_cork_oak_trunk/t_cork_oak_trunk_b.color.png',
      detailMap: '/assets/materials/tree/tropical/tro_tree_1_trunk/t_tropical_bark_variation_1_detail.data.png',
      detailNormalMap: '/assets/materials/tree/tropical/tro_tree_1_trunk/t_tro_bark_01_detail_nm.normal.png',
      detailScale: [0.5, 0.25],
      normalMap: '/assets/materials/tree/cork_oak/t_cork_oak_trunk/t_cork_oak_trunk_nm.normal.png',
      normalMapStrength: 1.5,
      roughnessMap: '/assets/materials/tree/cork_oak/t_cork_oak_trunk/t_cork_oak_trunk_r.data.png',
    }],
    alphaRef: 85,
    annotation: 'NATURE',
    groundType: 'WOOD',
  },
  holm_oak_branches: {
    name: 'holm_oak_branches',
    mapTo: 'holm_oak_branches',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/holm_oak/t_holm_oak_branches/t_holm_oak_branches_ao.data.png',
      baseColorMap: '/assets/materials/tree/holm_oak/t_holm_oak_branches/t_holm_oak_branches_b.color.png',
      detailNormalMap: '/assets/materials/tree/cork_oak/cork_oak_trunk/t_cork_oak_trunk_nm.normal.png',
      detailNormalMapStrength: 3,
      detailScale: [2, 4],
      normalMap: '/assets/materials/tree/holm_oak/t_holm_oak_branches/t_holm_oak_branches_nm.normal.png',
      opacityMap: '/assets/materials/tree/holm_oak/t_holm_oak_branches/t_holm_oak_branches_o.data.png',
      roughnessMap: '/assets/materials/tree/holm_oak/t_holm_oak_branches/t_holm_oak_branches_r.data.png',
    }],
    alphaRef: 70,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 0.00999999978,
  },
  m_cork_oak_distant: {
    name: 'm_cork_oak_distant',
    mapTo: 'm_cork_oak_distant',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/assets/materials/tree/cork_oak/t_cork_oak_distant/t_cork_oak_distant_ao.data.png',
      baseColorMap: '/assets/materials/tree/cork_oak/t_cork_oak_autumn_distant/t_cork_oak_autumn_distant_b.color.png',
      normalMap: '/assets/materials/tree/cork_oak/t_cork_oak_distant/t_cork_oak_distant_nm.normal.png',
      opacityMap: '/assets/materials/tree/cork_oak/t_cork_oak_distant/t_cork_oak_distant_o.data.png',
      roughnessMap: '/assets/materials/tree/cork_oak/t_cork_oak_distant/t_cork_oak_distant_r.data.png',
    }],
    alphaRef: 75,
    alphaTest: true,
    doubleSided: true,
    dynamicCubemap: true,
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 1,
  },
  leaves_strong: {
    name: 'leaves_strong',
    mapTo: 'leaves_strong',
    class: 'Material',
    Stages: [{}, {}, {}, {}],
    groundType: 'leaves_strong',
    groundDepth: 0.6000000238418579,
  },
  GrassMiddle: {
    name: 'GrassMiddle',
    mapTo: 'GrassMiddle',
    class: 'Material',
    Stages: [{
      colorMap: '/assets/materials/foliage/grass/GrassMiddle/Grass_Middle_d.dds',
      normalMap: '/assets/materials/foliage/grass/GrassDry/Grass_green_n.normal.png',
      specularMap: '/assets/materials/foliage/grass/GrassDry/Grass_green_s.color.png',
      useAnisotropic: true,
    }],
    alphaRef: 95,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    groundType: 'GRASS',
    translucentBlendOp: 'None',
  },
};

const JOHNSON_VALLEY_RUNTIME_MATERIAL_DEFS = {
  ...UTAH_RUNTIME_MATERIAL_DEFS,
  deserttree_trunk: {
    name: 'deserttree_trunk',
    mapTo: 'deserttree_trunk',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_trunk_ao.data.png',
      baseColorMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_trunk_b.color.png',
      detailNormalMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_trunk_nm.normal.png',
      detailScale: [8, 8],
      normalMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_trunk_nm.normal.png',
      roughnessMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_trunk_r.data.png',
    }, {}, {}, {}],
    annotation: 'NATURE',
    groundType: 'FOREST',
  },
  deserttree_branches: {
    name: 'deserttree_branches',
    mapTo: 'deserttree_branches',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_branches_ao.data.png',
      baseColorMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_branches_b.color.png',
      normalMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_branches_nm.normal.png',
      opacityMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_branches_o.data.png',
      roughnessMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_branches_r.data.png',
    }, {}, {}, {}],
    alphaRef: 65,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    groundType: 'FOREST',
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 0.00999999978,
  },
  deserttree_leaves: {
    name: 'deserttree_leaves',
    mapTo: 'deserttree_leaves',
    class: 'Material',
    Stages: [{
      baseColorMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_leaves_b.color.png',
      detailScale: [1, 1],
      normalMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_leaves_nm.normal.png',
      opacityMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_leaves_o.data.png',
      roughnessMap: '/levels/johnson_valley/art/shapes/trees/deserttrees/t_desert_tree_leaves_r.data.png',
    }, {}, {}, {}],
    alphaRef: 65,
    alphaTest: true,
    annotation: 'NATURE',
    doubleSided: true,
    groundType: 'LEAVES_STRONG',
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 1,
  },
  leaves_thin: {
    name: 'leaves_thin',
    mapTo: 'leaves_thin',
    class: 'Material',
    Stages: [{}, {}, {}, {}],
    groundType: 'leaves_thin',
    groundDepth: 1,
  },
  branches_strong: {
    name: 'branches_strong',
    mapTo: 'branches_strong',
    class: 'Material',
    Stages: [{}, {}, {}, {}],
    groundType: 'branches_strong',
    groundDepth: 1,
  },
  rocks_desert_ca: {
    name: 'rocks_desert_ca',
    mapTo: 'rocks_desert_ca',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/johnson_valley/art/shapes/rocks/t_rocks_desert_ca_ao.data.png',
      baseColorFactor: [0.896924973, 0.896915972, 0.896915972, 1],
      baseColorMap: '/levels/johnson_valley/art/shapes/rocks/t_rocks_desert_ca_b.color.png',
      detailMap: '/levels/johnson_valley/art/shapes/rocks/t_rocks_pac_detail_b.data.png',
      detailNormalMap: '/levels/johnson_valley/art/shapes/rocks/t_rocks_pac_detail_n.normal.png',
      detailNormalMapStrength: 0.699999988,
      detailScale: [32, 16],
      normalMap: '/levels/johnson_valley/art/shapes/rocks/t_rocks_desert_ca_nm.normal.png',
      roughnessMap: '/levels/johnson_valley/art/shapes/rocks/t_rocks_desert_ca_r.data.png',
    }, {}, {}, {}],
    annotation: 'ROCK',
    groundType: 'ROCK',
    translucentBlendOp: 'None',
  },
};

const JUNGLE_ROCK_ISLAND_RUNTIME_MATERIAL_DEFS = {
  BNG_Grass_03: {
    name: 'BNG_Grass_03',
    mapTo: 'unmapped_mat',
    class: 'Material',
    Stages: [{
      colorMap: '/levels/jungle_rock_island/art/shapes/groundcover/grass/Grass_Green_d.color.DDS',
      diffuseColor: [0.999997973, 1, 0.999989986, 1],
      normalMap: '/levels/jungle_rock_island/art/shapes/groundcover/grass/Grass_Green_n.dds',
      pixelSpecular: true,
      roughnessFactor: 0.662999988,
      specularMap: '/levels/jungle_rock_island/art/shapes/groundcover/grass/Grass_Green_s.dds',
      useAnisotropic: true,
    }, {}, {}, {}],
    alphaRef: 79,
    alphaTest: true,
    annotation: 'GRASS',
    doubleSided: true,
    groundType: 'GRASS',
  },
  vegetation_palm_02: {
    name: 'vegetation_palm_02',
    mapTo: 'vegetation_palm_02',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_leaves_ao.data.png',
      baseColorFactor: [0.996078014, 0.996078014, 0.996078014, 1],
      baseColorMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_leaves_b.color.png',
      normalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_leaves_nm.normal.png',
      opacityMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_leaves_o.data.png',
      roughnessMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_leaves_r.data.png',
      specular: [0.996078014, 0.996078014, 0.996078014, 1],
    }, {}, {}, {}],
    alphaRef: 107,
    alphaTest: true,
    doubleSided: true,
    groundType: 'LEAVES_THIN',
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 0.800000012,
  },
  vegetation_palm_02_single_side: {
    name: 'vegetation_palm_02_single_side',
    mapTo: 'vegetation_palm_02_single_side',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_leaves_ao.data.png',
      baseColorFactor: [0.996078014, 0.996078014, 0.996078014, 1],
      baseColorMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_leaves_b.color.png',
      detailNormalMapStrength: 0.300000012,
      detailScale: [4, 4],
      normalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_leaves_nm.normal.png',
      opacityMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_leaves_o.data.png',
      roughnessFactor: 0.672736585,
      roughnessMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_leaves_r.data.png',
      specular: [0.996078014, 0.996078014, 0.996078014, 1],
    }, {}, {}, {}],
    alphaRef: 107,
    alphaTest: true,
    groundType: 'LEAVES_THIN',
  },
  vegetation_palm_trunk: {
    name: 'vegetation_palm_trunk',
    mapTo: 'vegetation_palm_trunk',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_trunk_ao.data.png',
      baseColorFactor: [0.996078014, 0.996078014, 0.996078014, 1],
      baseColorMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_trunk_b.color.png',
      detailNormalMapStrength: 1.20000005,
      detailScale: [0.100000001, 0.100000001],
      normalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_trunk_nm.normal.png',
      roughnessMap: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/t_palm_trunk_r.data.png',
    }, {}, {}, {}],
    groundType: 'WOOD',
    translucentBlendOp: 'None',
  },
  tro_tree_1_trunk: {
    name: 'tro_tree_1_trunk',
    mapTo: 'tro_tree_1_trunk',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_bark_01_ao.data.png',
      baseColorFactor: [1, 0.999994993, 0.999989986, 1],
      baseColorMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_bark_01_b.color.png',
      detailMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_bark_01_detail.data.png',
      detailNormalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_bark_01_detail_nm.normal.png',
      detailScale: [0.400000006, 0.400000006],
      normalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_bark_01_nm.normal.png',
      roughnessMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_bark_01_r.data.png',
    }, {}, {}, {}],
    groundType: 'WOOD',
  },
  tro_tree_1_branches: {
    name: 'tro_tree_1_branches',
    mapTo: 'tro_tree_1_branches',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_branch_01_ao.data.png',
      baseColorMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_branch_01_b.color.png',
      normalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_branch_01_nm.normal.png',
      opacityMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_branch_01_o.data.png',
      roughnessMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_branch_01_r.data.png',
    }, {}, {}, {}],
    alphaRef: 51,
    alphaTest: true,
    doubleSided: true,
    groundType: 'LEAVES_STRONG',
  },
  tro_tree_1_leaves: {
    name: 'tro_tree_1_leaves',
    mapTo: 'tro_tree_1_leaves',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_tree_01_leaves_ao.data.png',
      baseColorMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_tree_01_leaves_b.color.png',
      normalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_tree_01_leaves_nm.normal.png',
      opacityMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_tree_01_leaves_o.data.png',
      roughnessMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_tree_01_leaves_r.data.png',
    }, {}, {}, {}],
    alphaRef: 60,
    alphaTest: true,
    doubleSided: true,
    groundType: 'LEAVES_THIN',
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 0.699999988,
    translucentBlendOp: 'None',
  },
  tro_tree_1_leaves_02: {
    name: 'tro_tree_1_leaves_02',
    mapTo: 'tro_tree_1_leaves_02',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_tree_01_leaves_02_ao.data.png',
      baseColorFactor: [0.999998987, 1, 0.999989986, 1],
      baseColorMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_tree_01_leaves_02_b.color.png',
      normalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_tree_01_leaves_02_nm.normal.png',
      opacityMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_tree_01_leaves_02_o.data.png',
      roughnessFactor: 0.800000012,
      roughnessMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_tree_01_leaves_02_r.data.png',
    }, {}, {}, {}],
    alphaRef: 90,
    alphaTest: true,
    doubleSided: true,
    groundType: 'LEAVES_THIN',
    subSurfaceIntensity: 0.708999991,
  },
  tro_tree_2_trunk: {
    name: 'tro_tree_2_trunk',
    mapTo: 'tro_tree_2_trunk',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_bark_02_ao.data.png',
      baseColorFactor: [1, 0.999994993, 0.999989986, 1],
      baseColorMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_bark_02_b.color.png',
      detailNormalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_1/t_tro_bark_01_detail_nm.normal.png',
      detailScale: [1, 0.200000003],
      normalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_bark_02_nm.normal.png',
      roughnessMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_bark_02_r.data.png',
    }, {}, {}, {}],
    groundType: 'WOOD',
  },
  tro_tree_2_branch: {
    name: 'tro_tree_2_branch',
    mapTo: 'tro_tree_2_branch',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_branch_02_ao.data.png',
      baseColorMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_branch_02_b.color.png',
      normalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_branch_02_nm.normal.png',
      opacityMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_branch_02_o.data.png',
      roughnessMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_branch_02_r.data.png',
    }, {}, {}, {}],
    alphaRef: 50,
    alphaTest: true,
    doubleSided: true,
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 0.0500000007,
  },
  tro_tree_2_leaves: {
    name: 'tro_tree_2_leaves',
    mapTo: 'tro_tree_2_leaves',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_tree_02_leaves_ao.data.png',
      baseColorFactor: [1, 0.999989986, 0.999989986, 1],
      baseColorMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_tree_02_leaves_b.color.png',
      detailNormalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/detail_normal_filler.normal.png',
      detailScale: [1, 1],
      normalMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_tree_02_leaves_nm.normal.png',
      opacityMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_tree_02_leaves_o.data.png',
      roughnessFactor: 0.809000015,
      roughnessMap: '/levels/jungle_rock_island/art/shapes/trees/trees_tropical_2/t_tro_tree_02_leaves_r.data.png',
    }, {}, {}, {}],
    alphaRef: 54,
    alphaTest: true,
    doubleSided: true,
    groundType: 'LEAVES_THIN',
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 1,
  },
  tro_vines_2d: {
    name: 'tro_vines_2d',
    mapTo: 'tro_vines_2d',
    class: 'Material',
    Stages: [{
      ambientOcclusionMap: '/levels/jungle_rock_island/art/shapes/trees/vines_tropical/t_tro_vines_ao.data.png',
      baseColorMap: '/levels/jungle_rock_island/art/shapes/trees/vines_tropical/t_tro_vines_b.color.png',
      normalMap: '/levels/jungle_rock_island/art/shapes/trees/vines_tropical/t_tro_vines_nm.normal.png',
      opacityMap: '/levels/jungle_rock_island/art/shapes/trees/vines_tropical/t_tro_vines_o.data.png',
      roughnessMap: '/levels/jungle_rock_island/art/shapes/trees/vines_tropical/t_tro_vines_r.data.png',
    }, {}, {}, {}],
    alphaRef: 67,
    alphaTest: true,
    doubleSided: true,
    groundType: 'LEAVES_THIN',
    invertBackFaceNormals: true,
    subSurface: true,
    subSurfaceIntensity: 0.0700000003,
  },
  leaves_strong: {
    name: 'leaves_strong',
    mapTo: 'leaves_strong',
    class: 'Material',
    Stages: [{}, {}, {}, {}],
    groundType: 'leaves_strong',
    groundDepth: 0.6000000238418579,
  },
  leaves_thin: {
    name: 'leaves_thin',
    mapTo: 'leaves_thin',
    class: 'Material',
    Stages: [{}, {}, {}, {}],
    groundType: 'leaves_thin',
    groundDepth: 1,
  },
  catchfence: UTAH_RUNTIME_MATERIAL_DEFS.catchfence,
};

const INDUSTRIAL_RUNTIME_MATERIAL_DEFS = {
  ...EAST_COAST_RUNTIME_MATERIAL_DEFS,
  ...AUTOMATION_TEST_TRACK_RUNTIME_MATERIAL_DEFS,
  catchfence: UTAH_RUNTIME_MATERIAL_DEFS.catchfence,
};

const FLAVOR_RUNTIME_MATERIAL_DEFS = {
  east_coast_usa: EAST_COAST_RUNTIME_MATERIAL_DEFS,
  hirochi_raceway: EAST_COAST_RUNTIME_MATERIAL_DEFS,
  Industrial: INDUSTRIAL_RUNTIME_MATERIAL_DEFS,
  industrial: INDUSTRIAL_RUNTIME_MATERIAL_DEFS,
  johnson_valley: JOHNSON_VALLEY_RUNTIME_MATERIAL_DEFS,
  jungle_rock_island: JUNGLE_ROCK_ISLAND_RUNTIME_MATERIAL_DEFS,
  italy: ITALY_RUNTIME_MATERIAL_DEFS,
  Utah: UTAH_RUNTIME_MATERIAL_DEFS,
  utah: UTAH_RUNTIME_MATERIAL_DEFS,
  automation_test_track: AUTOMATION_TEST_TRACK_RUNTIME_MATERIAL_DEFS,
};

export function getFlavorRuntimeMaterialDefs(flavor) {
  const levelName = typeof flavor === 'string' ? flavor : flavor?.levelName;
  return FLAVOR_RUNTIME_MATERIAL_DEFS[levelName] ?? {};
}
